# Generated by Django 2.1.5 on 2019-04-16 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookupcode', models.CharField(max_length=30)),
                ('lookname', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('Inactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lookupdet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookupdetdesc', models.CharField(max_length=200)),
                ('lookupvalue', models.CharField(max_length=100)),
                ('lookuplevel', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('Inactive', 'inactive')], default='active', max_length=10)),
                ('lookup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup.Lookup')),
            ],
            options={
                'ordering': ('lookupdetdesc',),
            },
        ),
    ]
