# Generated by Django 2.2 on 2019-04-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_code', models.CharField(max_length=5)),
                ('object_desc', models.CharField(max_length=200)),
                ('object_compcode', models.CharField(max_length=20)),
                ('lookup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Object_master', to='lookup.Lookupdet')),
                ('object_parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountcode.Object_master')),
            ],
            options={
                'db_table': 'object_master',
            },
        ),
        migrations.CreateModel(
            name='Function_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_code', models.CharField(max_length=5)),
                ('function_desc', models.CharField(max_length=200)),
                ('function_compcode', models.CharField(max_length=20)),
                ('function_parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountcode.Function_master')),
                ('lookup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Function_master', to='lookup.Lookupdet')),
            ],
            options={
                'db_table': 'function_master',
            },
        ),
    ]
