# Generated by Django 2.2.1 on 2019-06-05 11:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=20)),
                ('receipt_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payer_name', models.CharField(max_length=200)),
                ('narration', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Receiptdet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_amt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt.Receipt')),
                ('subledger_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subledger', to='subledger.Subledger_master')),
            ],
        ),
    ]
