# Generated by Django 2.1.5 on 2019-04-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankcode', models.CharField(max_length=20)),
                ('bankname', models.CharField(max_length=100)),
                ('branch', models.TextField(max_length=200)),
                ('bankaddress', models.CharField(max_length=500)),
            ],
        ),
    ]
