# Generated by Django 2.1.7 on 2019-05-29 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subledger', '0001_initial'),
        ('bankmaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmasterdet',
            name='subledgeraccountcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SUBLEDGER', to='subledger.Subledger_master'),
        ),
    ]
