# Generated by Django 2.2 on 2019-05-03 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subledger', '0001_initial'),
        ('bankmaster', '0002_bankmasterdet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmasterdet',
            name='subledgeraccountcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SUBLEDGER', to='subledger.Subledger_master'),
        ),
    ]
